
### loop orders and locality  {.smaller}


* loop body: $C_ij += A_ikB_kj$
* $ki[j]{.fragment fragment-index=2 .custom .myem-only}$ order: $C_i[j]{.fragment fragment-index=2 .custom .myem-only}$, $B_k[j]{.fragment fragment-index=2 .custom .myem-only}$ have [spatial locality]{.fragment fragment-index=1 .custom .myem-only}
* $kij$ order: $A_ik$ has [temporal locality]{.fragment fragment-index=1 .custom .myem-only}
* … better than …
* $ij[k]{.fragment fragment-index=2 .custom .myem-only}$ order: $A_i[k]{.fragment fragment-index=2 .custom .myem-only}$ has spatial locality
* $ijk$ order: $C_ij$ has temporal locality


### matrix multiply  {.smaller}

\[ C_{ij} = \sum_{k=1}^n A_{ik}\times B_{kj} \] <!-- \lstset{
    style=small,
    language=C,
    moredelim=**[is][\btHL<2>]{~2}{~},
    moredelim=**[is][\btHL<3>]{~3}{~},
    moredelim=**[is][\btHL<4>]{~4}{~},
} -->
 
<pre><code>/* version 1: inner loop is k, middle is j*/
for (int i = 0; i &lt; N; ++i)
  for (int j = 0; j &lt; N; ++j)
    for (int k = 0; k &lt; N; ++k)
      <span data-fragment-index="3" class="fragment custom myem-only">C[i*N+j]</span> += A\[i * N + <span data-fragment-index="2" class="fragment custom myem-only">k</span>] * B\[k * N + j];

/* version 2: outer loop is k, middle is i */
for (int k = 0; k &lt; N; ++k)
  for (int i = 0; i &lt; N; ++i)
    for (int j = 0; j &lt; N; ++j)
      C\[i*N+<span data-fragment-index="2" class="fragment custom myem-only">j</span>] += <span data-fragment-index="3" class="fragment custom myem-only">A[i * N + k]</span> * B\[k * N + <span data-fragment-index="2" class="fragment custom myem-only">j</span>];
</code></pre>

