
### one possible implementation  {.smaller}


<pre><code>struct Mutex { 
    <span data-fragment-index="2" class="fragment custom myem-only">SpinLock guard_spinlock;</span>
    <span data-fragment-index="3" class="fragment custom myem-only">bool lock_taken = false;</span>
    <span data-fragment-index="4" class="fragment custom myem-only">WaitQueue wait_queue;</span>
};
</code></pre>
 
:::: {.columns}

::: {.column width="45%"}
 
<pre><code>LockMutex(Mutex *m) {
  LockSpinlock(&amp;m-&gt;guard_spinlock);
  if (m-&gt;lock_taken) {
    put current thread on m-&gt;wait_queue
    mark current thread as waiting
    /* xv6: myproc()-&gt;state = SLEEPING; */
    <span class="fragment custom myem-only" data-fragment-index="7"><span class="fragment custom myem-only" data-fragment-index="8">UnlockSpinlock(&amp;m-&gt;guard_spinlock);</span></span>
    <span class="fragment custom myem-only" data-fragment-index="7"><span class="fragment custom myem-only" data-fragment-index="8">run scheduler (context switch)</span></span>
  } else {
    m-&gt;lock_taken = true;
    UnlockSpinlock(&amp;m-&gt;guard_spinlock);
  }
}
</code></pre>
 
:::

::: {.column width="45%"}
 
<pre><code>UnlockMutex(Mutex *m) {
  LockSpinlock(&amp;m-&gt;guard_spinlock);
  if (m-&gt;wait_queue not empty) {
    <span data-fragment-index="6" class="fragment custom myem-only">remove a thread from m-&gt;wait_queue</span> 
    <span data-fragment-index="6" class="fragment custom myem-only">mark thread as no longer waiting</span>
    /* xv6: myproc()-&gt;state = RUNNABLE; */
  } else {
     m-&gt;lock_taken = false;
  }
  UnlockSpinlock(&amp;m-&gt;guard_spinlock);
}
</code></pre>
 
:::

::::

::: {.myoverbox .fragment fragment-index=2 .vlow .fade-in-then-out}

spinlock protecting `lock_taken` and `wait_queue` <br/>
only held for very short amount of time (compared to mutex itself)

:::

::: {.myoverbox .fragment fragment-index=3 .vlow .fade-in-then-out}

tracks whether any thread has locked and not unlocked

:::

::: {.myoverbox .fragment fragment-index=4 .vlow .fade-in-then-out}

list of threads that discovered lock is taken <br/>
and are waiting for it be free <br>
these threads are _not runnable_

:::

::: {.myoverbox .fragment fragment-index=6 .vlow .fade-in-then-out}

instead of setting `lock_taken` to false <br/>
choose thread to hand-off lock to

:::

::: {.myoverbox .fragment fragment-index=7 .vlow .fade-in-then-out}

subtly: if UnlockMutex runs here on another core <br/>
need to make sure scheduler on the other core doesn't switch to thread <br/>
while it is still running (would 'clone' thread/mess up registers)

:::
