
### producer/consumer constraints  {.smaller}


* consumer waits for producer(s) if buffer is empty
* producer waits for consumer(s) if buffer is full
* any thread waits while a thread is manipulating the buffer 
<hr class="vspace" />
* <em>one semaphore per constraint</em>: 
```c
sem_t full_slots;   // consumer waits if empty
sem_t empty_slots;  // producer waits if full
sem_t mutex;        // either waits if anyone changing buffer
FixedSizedQueue buffer;
```



### producer/consumer pseudocode  {.smaller .longcode}


```{.c code-line-numbers=true}
{{< include /sync-semaphores/producer-consumer.c >}}
```

### producer/consumer psuedocode --- semaphores {.smaller}

```{.c code-line-numbers="1-2"}
{{< include /sync-semaphores/producer-consumer.c >}}
```

::: {.myoverbox .midright}

`full_slots` $\le$ # items on queue <br/>
`empty_slots` $\le$ # free slots on queue<br />

:::

### producer/consumer psuedocode --- exercise 1 {.smaller}

```{.c code-line-numbers=true}
{{< include /sync-semaphores/producer-consumer.c >}}
```

::: {.myoverbox .midright style="width: 50%"}

exercise: when is `full_slots` value + `empty_slots` value != queue size?

:::

### producer/consumer psuedocode --- exercise 2 {.smaller}

```{.c code-line-numbers="7-8"}
{{< include /sync-semaphores/producer-consumer.c >}}
```

:::: {.myoverbox .highright style="width: 50%"}

can we do 
```c
sem_wait(&mutex);
sem_wait(&empty_slots);
```
instead in Produce()?

::: {.fragment}

<em>No</em> Consumer waits on `sem_wait(&mutex)`<br/>
so can't `sem_wait(&empty_slots)` (deadlock)

:::

::::

### producer/consumer: cannot reorder mutex/empty  {.smaller}


:::: {.columns}

::: {.column width="45%"}

```
ProducerReordered() {
  // BROKEN: WRONG ORDER
  sem_wait(&mutex);
  sem_wait(&empty_slots);

  ...

  sem_post(&mutex);

```

:::

::: {.column width="45%"}

```
Consumer() {
  sem_wait(&full_slots);

  // can't finish until
  // Producer's sem_post(&mutex):
  sem_wait(&mutex);

  ...
    
  // so this is not reached
  sem_post(&full_slots);

```

:::

::::

### producer/consumer psuedocode --- exercise 3 {.smaller}

```{.c code-line-numbers="10-12"}
{{< include /sync-semaphores/producer-consumer.c >}}
```

:::: {.myoverbox .midright style="width: 50%"}

can we do 
```c
sem_post(&full_slots);
sem_post(&mutex);
```
instead in Produce()?

::: {.fragment}

<em>Yes</em>

:::

::::


### producer/consumer summary  {.smaller}


* producer: wait (down) empty_slots, post (up) full_slots
* consumer: wait (down) full_slots, post (up) empty_slots 
<hr class="vspace" />
* two producers or consumers? 

   * still works!


