
# overall themes {visibility="hidden"}

### themes {.smaller}

* automating buidling software
    *  libraries, taking advantage of incremental compilation
* sharing machines
    *  multiple users/programs on one system
* parallelism and concurrency
    *  doing two+ things at once
* communicating between machines
    *  layered design of networks
    *  implementing secure communication
* making processors fast
    *  caching, (hidden) parallelism, avoiding idle time

### themes {.smaller}

* _automating buidling software_
    *  libraries, taking advantage of incremental compilation
* sharing machines
    *  multiple users/programs on one system
* parallelism and concurrency
    *  doing two+ things at once
* communicating between machines
    *  layered design of networks
    *  implementing secure communication
* making processors fast
    *  caching, (hidden) parallelism, avoiding idle time


# briefly, building {visibility="hidden"}

{{< include /intro/_make.qmd >}}

# briefly, virtual memory {visibility="hidden"}

### themes {.smaller}

* automating buidling software
    *  libraries, taking advantage of incremental compilation
* _sharing machines_
    *  multiple users/programs on one system
* parallelism and concurrency
    *  doing two+ things at once
* communicating between machines
    *  layered design of networks
    *  implementing secure communication
* making processors fast
    *  caching, (hidden) parallelism, avoiding idle time


{{< include /vm/_translationOverview.qmd >}}

{{< include /vm/_addrSpaceOnly.qmd >}}

## interrupts {visibility="hidden"}

### themes {.smaller}

* automating buidling software
    *  libraries, taking advantage of incremental compilation
* _sharing machines_
    *  multiple users/programs on one system
* _parallelism and concurrency_
    *  doing two+ things at once
* communicating between machines
    *  layered design of networks
    *  implementing secure communication
* making processors fast
    *  caching, (hidden) parallelism, avoiding idle time

{{< include /kernel/_keyInTimeline.qmd >}}

{{< include /kernel/_timeMulti.qmd >}}

{{< include /intro/_multi-core-time.qmd >}}

## kernel mode / permissions {visibility="hidden"}

{{< include /intro/_permissions-limit.qmd >}}

# networking {visibility="hidden"}

### themes {.smaller}

* automating buidling software
    *  libraries, taking advantage of incremental compilation
* sharing machines
    *  multiple users/programs on one system
* parallelism and concurrency
    *  doing two+ things at once
* _communicating between machines_
    *  layered design of networks
    *  implementing secure communication
* making processors fast
    *  caching, (hidden) parallelism, avoiding idle time


## layered design {visibility="hidden"}

{{< include /network/_layers-list.qmd >}}

## addresses and names {visibility="hidden"}

{{< include /network/_names-and-addresses.qmd >}}

## secure communication {visibility="hidden"}

### secure communication? 

* how do you know who your socket is to?
* who can read what's on the socket?
* what can you do to restrict this?

# caching {visibility="hidden"}

### themes {.smaller}

* automating buidling software
    *  libraries, taking advantage of incremental compilation
* sharing machines
    *  multiple users/programs on one system
* parallelism and concurrency
    *  doing two+ things at once
* communicating between machines
    *  layered design of networks
    *  implementing secure communication
* _making processors fast_
    *  caching, (hidden) parallelism, avoiding idle time

{{< include /caching/_memHierarchyPic.qmd >}}

# instruction-level parallelism {visibility="hidden"}

{{< include /intro/_perf-examples.qmd >}}

# C review {visibility="hidden"}

{{< include /intro/_cCheck.qmd >}}

{{< include /intro/_cCheck2.qmd >}}

{{< include /intro/_selectedC.qmd >}}
