### 1-level exercise (2)  {.vm-contents-exercise}

::: {.vm-contents-top}

6-bit virtual addresses, 6-bit physical; 8 byte pages, 1 byte PTE<br/>
page tables 1 page; PTE: 3 bit PPN (MSB), 1 valid bit, 4 other;<br/>
page table base register <code>0x20</code>; translate virtual address <code>0x12</code>

:::

::::: {.columns}

:::: {.column width="31%"}

<table>
<colgroup><col class="physadd" /><col class="bytes" /></colgroup>
<tr><th>physical address</th><th>bytes</th></tr>
<tr><td>0x00-03</td><td>00 11 22 33</td></tr>
<tr><td>0x04-07</td><td>44 55 66 77</td></tr>
<tr><td>0x08-0B</td><td>88 99 AA BB</td></tr>
<tr><td>0x0C-0F</td><td>CC DD EE FF</td></tr>
<tr><td>0x10-13</td><td>1A 2A 3A 4A</td></tr>
<tr><td>0x14-17</td><td>1B 2B 3B 4B</td></tr>
<tr><td>0x18-1B</td><td>1C 2C 3C 4C</td></tr>
<tr><td>0x1C-1F</td><td>1C 2C 3C 4C</td></tr>
</table>

::::

:::: {.column width="31%"}

<table>
<colgroup><col class="physadd" /><col class="bytes" /></colgroup>
<tr><th>physical address</th><th>bytes</th></tr>
<tr><td>[0x20-23]{.myem-only .custom .fragment fragment-index=3}</td><td>A0 E2 [D1]{.myem-only .custom .fragment fragment-index=4} F3</td></tr>
<tr><td>0x24-24</td><td>E4 E5 F6 07</td></tr>
<tr><td>0x28-2B</td><td>89 9A AB BC</td></tr>
<tr><td>0x2C-2F</td><td>CD DE EF F0</td></tr>
<tr><td>[0x30-33]{.myem-only .custom .fragment fragment-index=8}</td><td>BA 0A [BA]{.myem-only .custom .fragment fragment-index=9} 0A</td></tr>
<tr><td>0x34-37</td><td>CB 0B CB 0B</td></tr>
<tr><td>0x38-3B</td><td>DC 0C DC 0C</td></tr>
<tr><td>0x3C-3F</td><td>EC 0C EC 0C</td></tr>
</table>

::::

:::: {.column .solve .fragment fragment-index=1 width="37%"}

0x31 = [01 0]{.myem-only .custom .fragment fragment-index=2 .colorOne}[010]{.myem-only .custom .fragment fragment-index=7 .colorTwo}<sub>TWO</sub> <br/>
PTE addr: <br/>
0x20 + [010]{.myem-only .custom .fragment fragment-index=2 .colorOne}<sub>TWO</sub> $\times$ 1 = [0x22]{.myem-only .custom .fragment .colorThree fragment-index=3}<br/>
PTE value: <br/>
[0xD1]{.myem-only .custom .fragment fragment-index=4} = [110]{.myem-only .custom .fragment fragment-index=5 .colorFour}[1]{.myem-only .custom .fragment fragment-index=6 .colorFive} 0001<sub>TWO</sub><br/>
PPN [110]{.myem-only .custom .fragment fragment-index=5 .colorFour}, valid [1]{.myem-only .custom .fragment fragment-index=6 .colorFive} <br/>
M\[[110]{.myem-only .custom .fragment fragment-index=5 .colorFour} [010]{.custom .fragment .myem-only fragment-index=7 .colorTwo}<sub>TWO</sub>\] = M\[[0x32]{.myem-only .custom .fragment fragment-index=8}]<br />$\rightarrow$ [0xBA]{.myem-only .custom .fragment fragment-index=9}

::::

:::::

