
### how does login work?  {.smaller}

::: {.columns}

::: {.column width="60%"}

```
somemachine login: jo
password: ********

jo@somemachine$ ls
...
```
 

* this is a program which…

  1. [checks if the password is correct]{.fragment fragment-index=2 .custom .myem-only}, and
  2. [changes user IDs]{.fragment fragment-index=3 .custom .myem-only}, and
  3. runs a shell

:::

::: {.column width="40%"}

```{mermaid}
%%| fig-width: 3
%%| fig-height: 4
flowchart TD
    A["/bin/login runs"] -->|"Check password"| B{Password correct?}
    B -->|Yes| C["Run setuid()"]
    C --> D["Run shell"]
    B -->|No| E[Retry]

```

:::

:::




<!-- ### againframe(loginProgram) -->

### Unix password storage  {.smaller}


* typical single-user system: <code>/etc/shadow</code> 

   * only readable by root/superuser

* department machines: network service 

   * Kerberos / Active Directory:
   * server takes (encrypted) passwords
   * server gives tokens: ‘‘yes, really this user’’
   * can cryptographically verify tokens come from server



### aside: beyond passwords  {.smaller}


* /bin/login entirely user-space code
* only thing special about it: when it's run
* could use any criteria to decide, not just passwords 

   * physical tokens
   * biometrics
   * …



<!-- ### againframe(loginProgram) -->

### changing user IDs   {.smaller}

::: {.columns}

::: {.column width="75%"}
```c
int setuid(uid_t uid);
```

* if superuser: sets effective user ID to arbitrary value

   * and a ‘‘real user ID'’ and a ‘‘saved set-user-ID’’ (we’ll talk later)

* system starts as superuser and login programs run as superuser

   * voluntarily restrict own access before running shell, etc.
:::

::: {.column width="25%"}

```{mermaid}
%%| fig-width: 2
%%| fig-height: 3
flowchart TD
    A["Process runs as superuser"] --> B[Do priviledged operations]
    B -->|"Call setuid(uid)"| C[Run shell as user]
```

:::

:::
