
# accounts {visibility="hidden"}

{{< include ../accounts/_intro.qmd >}}

# user ID idea {visibility="hidden"}

{{< include ../accounts/_user-id.qmd >}}

## group IDs {visibility="hidden"}

{{< include ../accounts/_group-id.qmd >}}

### user id and group id establish _identity_


* _who_ is running a process or accessing a resource
* but also need _permissions_

   * what users can access
```{mermaid}
%%| fig-width: 5
%%| fig-height: 3

block-beta
  columns 3
  %% Userspace processes on one line
  block:Userspace:3
    columns 3
    T["Userspace"]:3
    P1["Process A\nUID: 858545"]
    P2["Process B\nUID: 103"]
    P3["Process C\nUID: 797979"]
  end


  I["open(/u/bradjc/private.txt, O_RDONLY)"]:3

  space:3

  D["Kernel"]:3


  P1 --> D
  P2 -- "deny" --> D
  P3 -- "deny" --> D


  style T fill:none,stroke:none;
  style I fill:#ddd,stroke:none;
  style Userspace stroke:none;
```


# permissions and access control lists {visibility="hidden"}

## file permissions {visibility="hidden"}

{{< include ../accounts/_file-chmod.qmd >}}

{{< include ../accounts/_file-acls.qmd >}}

### ACLs establish permissions 


* identity: _who_ is running a process or accessing a resource
* permissions: who has _what access_ to a file or resource
* now need _enforcement_

   * ensure that permissions are implemented correctly



# enforcing permissions {visibility="hidden"}

{{< include ../accounts/_auth-unix-check.qmd >}}

# superuser {visibility="hidden"}

{{< include ../accounts/_auth-unix-superuser.qmd >}}

# becoming superuser {visibility="hidden"}

## on boot, /bin/login {visibility="hidden"}

{{< include ../accounts/_bin-login.qmd >}}

## set-user-ID/sudo {visibility="hidden"}

{{< include ../accounts/_sudo.qmd >}}

{{< include ../accounts/_setuid-use.qmd >}}

## a litany of silly setuid program issues {visibility="hidden"}

{{< include ../accounts/_setuid-hard-to-write.qmd >}}

# privilege escalation {visibility="hidden"}

{{< include ../accounts/_priv-escalate.qmd >}}
