
### quizzes  {.smaller}


* released evening after Thursday lecture 

   * starting <it>next</it> week

* due 15 minutes before \textbf{first} lecture on Tuesdays 

* about lecture and/or lab from the prior week
* 4--5ish questions
* <it>individual</it>, open book, open notes, open Internet


### quizzes and work/comments 


* quizzes will have place for comments/work 

* will be used to do grading 

   * delay: about 1 week after quiz is due

* please use so we can give partial credit
* if you find possible error in quiz question <br> please make your best guess about was meant <br> and explain what you did in the comemnts


### on help on quiz questions 


* I and the TAs won't answer quiz questions…
* but we will answer questions about the lecture material, etc. 

* (and TAs (not you) are responsible for knowing <br> what they can't answer <br> but we'd prefer you don't try to test those limits)


### going over past quizzes 


* have in past gone over quiz Qs in lecture 

   * either when a lot missed it or <br> on request in lecture

* also fine office hour/Piazza question

