### last time {.smaller}

*  tracking mmap-type "memory regions"
   *  range of virtual addresses
   *  optional backing file (file to load from), location in file
   *  private (copy-on-write from backing file) or shared mappings
*  on page fault: fill in from memory region list
   *  determine what (if anything) "should" be there
   *  how OS decides to load-on-demand, copy-on-write, etc. or crash
*  page tables in memory
   *  representing entries as integers
   *  array of integers in memory
   *  special <i>base pointer</i> register

## exercise (alt 2): page table in memory {visibility="hidden"}

{{< include /vm-format/_multiSplitExPt1c.qmd >}}

## assignment preview 1 {visibility="hidden"}

{{< include /vm-format/_asgnSetup.qmd >}}

{{< include /vm-format/_asgnPageAccess.qmd >}}

{{< include /vm-format/_toyLookupAsgn.qmd >}}

# handling big page tables {visibility="hidden"}

## the problem {visibility="hidden"}

{{< include /vm-format/_ptSize64A.qmd >}}

## general options {visibility="hidden"}

{{< include /vm-format/_bigPageOptions.qmd >}}

## two-level page tables {visibility="hidden"}

{{< include /vm-format/_twoLevelPT.qmd >}}

{{< include /vm-format/_twoLevelPtLib.qmd >}}

{{< include /vm-format/_twoLevelPTAlt.qmd >}}

## more than two levels {visibility="hidden"}

{{< include /vm-format/_multiLevelGen.qmd >}}

## page table counting

{{< include /vm-format/_threeLevelCountingEx.qmd >}}

{{< include /vm-format/_countingBestWorst.qmd >}}

{{< include /vm-format/_multiChoice.qmd >}}

## exercises: multi-level lookup {visibility="hidden"}

## part 2{visibility="hidden"}

{{< include /vm-format/_multiSplitExPt2.qmd >}}


## part 3{visibility="hidden"}

{{< include /vm-format/_multiSplitExPt3.qmd >}}

## exercise interlude: parameters

{{< include /vm-format/_multiParamExercise.qmd >}}

{{< include /vm-format/_multiSplitExPt3b.qmd >}}

## part 4{visibility="hidden"}

{{< include /vm-format/_multiSplitExPt4.qmd >}}
{{< include /vm-format/_multiSplitExPt4b.qmd >}}

## part 5{visibility="hidden"}

{{< include /vm-format/_multiSplitExPt5.qmd >}}

###

### backup slides



## exercise (alt): page table in memory {visibility="hidden"}

{{< include /vm-format/_multiSplitExPt1b.qmd >}}
