### last time {.smaller}

*  fork examples
   *  all memory, registers copied = independent variables
   *  program counter copied = execution of child starts at fork() 
   *  execution keeps until exit
      *  don't think `if (p == 0) { ... } ...` stops it
*  waitpid
   *  wait for child process (of current process) if needed
   *  collects "status" (how terminated, reason/exit code)
   *  OS keeps status info around until you collect it
*  exec
   *  places running program in current process
   *  if successful, does not return --- instead your memory replaced with new program's stuff
*  fork/wait/exec pattern

### test 1

### practice test 1 {.smaller}

*  some changelog notes:
   *  missing .h in prereqs in makefile MC question
   *  timer exception corner case in exception timeline question
   *  clarification on "most likely" in exception timeline question
*  a note on context switching
   *  OS policies about when process context switches are triggered vary
   *  but need to be running OS in kernel mode to do that
   *  timer interrupt is "last resort" way to ensure OS runs

## exercises (fork+exec+wait) {visibility="hidden"}

{{< include /unix-api/_fork-wait-ex.qmd >}}

# shell features {visibility="hidden"}

{{< include /unix-api/_shell-features.qmd >}}

<!-- # fd management {visibility="hidden"}

## I/O redirection: syntax, method preview {visibility="hidden"} -->

# files in POSIX, part 1 {visibility="hidden"}

## interlude: file descriptors {visibility="hidden"}

{{< include /unix-api/_fds.qmd >}}

{{< include /unix-api/_special-fds.qmd >}}

## getting file descriptors {visibility="hidden"}

{{< include /unix-api/_open-quick.qmd >}}

{{< include /unix-api/_open-flags.qmd >}}

## close {visibility="hidden"}

{{< include /unix-api/_close.qmd >}}

## Shell: redirection {visibility="hidden"}

{{< include /unix-api/_redirection.qmd >}}

{{< include /unix-api/_redirection-exec.qmd >}}

## dup2: redirection mechanism {visibility="hidden"}

{{< include /unix-api/_dup.qmd >}}

## shell redirection examples {visibility="hidden"}

{{< include /unix-api/_redirection-example.qmd >}}

## open/close/dup/fork and fd array {visibility="hidden"}

{{< include /unix-api/_dup-close-and-array.qmd >}}

## dup2 exercise {visibility="hidden"}

{{< include /unix-api/_dup-ex.qmd >}}

## shared/unshared seek pointers {visibility="hidden"}

{{< include /unix-api/_seek-ptr.qmd >}}

## dup2 exercise (alt) {visibility="hidden"}

{{< include /unix-api/_read-write-ex.qmd >}}

# POSIX api summary {visibility="hidden"}

{{< include /unix-api/_summary.qmd >}}

## fork exercise 3 {visibility="hidden"}

{{< include /unix-api/_fork-ex3.qmd >}}

# virtual memory {visibility="hidden"}

## address spaces {visibility="hidden"}

{{< include /vm-intro/_recallAddr.qmd >}}

{{< include /vm-intro/_motivation.qmd >}}

{{< include /vm-intro/_addrSpaceOnly.qmd >}}

## address translation overview {visibility="hidden"}

{{< include /vm-intro/_translationOverview.qmd >}}

## simple paging with four pages {visibility="hidden"}

{{< include /vm-intro/_fourPages.qmd >}}

## on address space sizes {visibility="hidden"}

{{< include /vm-intro/_sizeNotes.qmd >}}


###

