
### exercise (1)  {.smaller}


* 1 set, 5-way cache, 4 byte blocks
* access pattern: 

   * 0x0, 0x1000, 0x4, 0x1004, 0x0, 0x1008, 0x4, 0x100C,
   * 0x0, 0x1010, 0x4, 0x1014, 0x0, 0x1018, 0x4, 0x101C,
   * 0x0, 0x1020, 0x4, 0x1024, 0x0, 0x1028, 0x4, 0x102C,
   * …

* how does each do? 

   * LRU
   * FIFO
   * random



### LRU  {.smaller}

<code></code>[]{.my-small} <table>
<tr><td>access</td><td>MRU $\\leftarrow{}\\rightarrow{}$ LRU</td></tr>
<tr><td>\only{* }0x0</td><td><em>0x0-3</em></td></tr>
<tr><td>0x1000</td><td><em>0x1000-3</em>, 0x0-3</td></tr>
<tr><td>\only{* }0x4</td><td><em>0x4-7</em>, 0x1000-3, 0x0-3</td></tr>
<tr><td>0x1004</td><td><em>0x1004-7</em>, 0x4-7, 0x1000-3, 0x0-3</td></tr>
<tr><td>0x0</td><td>0x0-3, 0x1004-7, 0x4-7, 0x1000-3</td></tr>
<tr><td>0x1008</td><td><em>0x1008-B</em>, 0x0-3, 0x1004-7, 0x4-7, 0x1000-3</td></tr>
<tr><td>0x4</td><td>0x4-7, 0x1008-B, 0x0-3, 0x1004-7, 0x1000-3</td></tr>
<tr><td>0x100C</td><td><em>0x100C-F</em>, 0x4-7, 0x1008-B, 0x0-3, 0x1004-7</td></tr>
<tr><td>0x0</td><td>0x0-3, 0x100C-F, 0x4-7, 0x1008-B, 0x1004-7</td></tr>
<tr><td>0x1010</td><td><em>0x1010-3</em>, 0x0-3, 0x100C-F, 0x4-7, 0x1008-B</td></tr>
<tr><td>…</td><td>…</td></tr>
<tr><td></td></tr>
</table>
 

* 0x0/0x4: 100% hit rate (after ‘warmup’)
* others: 0% hit rate


### FIFO (1)  {.smaller}

<code></code>[]{.my-small} <table>
<tr><td><code></code>[]{.my-small} access</td><td>last in $\\leftarrow{}\\rightarrow{}$ first in</td></tr>
<tr><td>\only{M }0x0</td><td><em>0x0-3</em></td></tr>
<tr><td>0x1000</td><td><em>0x1000-3</em>, 0x0-3</td></tr>
<tr><td>\only{M }0x4</td><td><em>0x4-7</em>, 0x1000-3, 0x0-3</td></tr>
<tr><td>0x1004</td><td><em>0x1004-7</em>, 0x4-7, 0x1000-3, 0x0-3</td></tr>
<tr><td>\only{H }0x0</td><td>0x1004-7, 0x4-7, 0x1000-3, 0x0-3</td></tr>
<tr><td>0x1008</td><td><em>0x1008-B</em>, 0x1004-7, 0x4-7, 0x1000-3, 0x0-3</td></tr>
<tr><td>\only{H }0x4</td><td>0x1008-B, 0x1004-7, 0x4-7, 0x1000-3, 0x0-3</td></tr>
<tr><td>0x100C</td><td><em>0x100C-F</em>, 0x1008-B, 0x1004-7, 0x4-7, 0x1000-3</td></tr>
<tr><td>\only{M }0x0</td><td><em>0x0-3</em>, 0x100C-F, 0x1008-B, 0x1004-7, 0x4-7</td></tr>
<tr><td>0x1010</td><td><em>0x1010-3</em>, 0x0-3, 0x100C-F, 0x1008-B, 0x1004-7</td></tr>
<tr><td>\only{M }0x4</td><td><em>0x4-7</em>, 0x1010-3, 0x0-3, 0x100C-F, 0x1008-B</td></tr>
<tr><td>0x1014</td><td><em>0x1014-7</em>, 0x4-7, 0x1010-3, 0x0-3, 0x100C-F</td></tr>
<tr><td>\only{H }0x0</td><td>0x1014-7, 0x4-7, 0x1010-3, 0x0-3, 0x100C-F</td></tr>
<tr><td>0x1018</td><td><em>0x1018-B</em>, 0x1014-7, 0x4-7, 0x1010-3, 0x0-3</td></tr>
<tr><td>\only{H }0x4</td><td>0x1018-B, 0x1014-7, 0x4-7, 0x1010-3, 0x0-3</td></tr>
<tr><td>0x101C</td><td><em>0x101C-F</em>, 0x1018-B, 0x1014-7, 0x4-7, 0x1010-3</td></tr>
<tr><td>\only{M }0x0</td><td><em>0x0-3</em>, 0x101C-F,  0x1018-B, 0x1014-7, 0x4-7</td></tr>
<tr><td>0x1020</td><td><em>0x1020-3</em>, 0x0-3, 0x101C-F,  0x1018-B, 0x1014-7</td></tr>
<tr><td>\only{M }0x4</td><td><em>0x0-4</em>, 0x1020-3, 0x101C-F,  0x1018-B, 0x1014-7</td></tr>
<tr><td>…</td><td>…</td></tr>
<tr><td></td></tr>
</table>


### FIFO (2)  {.smaller}

<code></code>[]{.my-small} <table>
<tr><td><code></code>[]{.my-small} access</td><td>last in $\\leftarrow{}\\rightarrow{}$ first in</td></tr>
<tr><td>…</td><td>…</td></tr>
<tr><td>&nbsp;&nbsp;0x100C</td><td><em>0x100C-F</em>, 0x1008-B, 0x1004-7, 0x4-7, 0x1000-3</td></tr>
<tr><td>\only{M }0x0</td><td><em>0x0-3</em>, 0x100C-F, 0x1008-B, 0x1004-7, 0x4-7</td></tr>
<tr><td>&nbsp;&nbsp;0x1010</td><td><em>0x1010-3</em>, 0x0-3, 0x100C-F, 0x1008-B, 0x1004-7</td></tr>
<tr><td>\only{M }0x4</td><td><em>0x4-7</em>, 0x1010-3, 0x0-3, 0x100C-F, 0x1008-B</td></tr>
<tr><td>&nbsp;&nbsp;0x1014</td><td><em>0x1014-7</em>, 0x4-7, 0x1010-3, 0x0-3, 0x100C-F</td></tr>
<tr><td>\only{H }0x0</td><td>0x1014-7, 0x4-7, 0x1010-3, 0x0-3, 0x100C-F</td></tr>
<tr><td>&nbsp;&nbsp;0x1018</td><td><em>0x1018-B</em>, 0x1014-7, 0x4-7, 0x1010-3, 0x0-3</td></tr>
<tr><td>\only{H }0x4</td><td>0x1018-B, 0x1014-7, 0x4-7, 0x1010-3, 0x0-3</td></tr>
<tr><td>&nbsp;&nbsp;0x101C</td><td><em>0x101C-F</em>, 0x1018-B, 0x1014-7, 0x4-7, 0x1010-3</td></tr>
<tr><td>\only{M }0x0</td><td><em>0x0-3</em>, 0x101C-F,  0x1018-B, 0x1014-7, 0x4-7</td></tr>
<tr><td>&nbsp;&nbsp;0x1020</td><td><em>0x1020-3</em>, 0x0-3, 0x101C-F,  0x1018-B, 0x1014-7</td></tr>
<tr><td>\only{M }0x4</td><td><em>0x0-4</em>, 0x1020-3, 0x101C-F,  0x1018-B, 0x1014-7</td></tr>
<tr><td>…</td><td>…</td></tr>
<tr><td></td></tr>
</table>
 

* 0x0/0x4: approx 50% hit rate (after ‘warmup’) <br> others: 0% hit rate

