
### thinking about cache storage (1)  {.smaller}


* 2KB direct-mapped cache with 16B blocks ---
* set 0: address 0 to 15\\tikzmark{first}, (0 to 15) +\\tikzmark{second} 2KB, (0 to 15) + 4KB, … 

   * block at 0: [array[0] through array[3]]{.fragment fragment-index=4 .custom .myem-only}
   * block at 0+2KB: [array[512] through array[515]]{.fragment fragment-index=4 .custom .myem-only}

* set 1: address 16 to 31, (16 to 31) + 2KB, (16 to 31) + 4KB, … <br> 

   * block at 16: array[4] through array[7]
   * block at 16+2KB: array[516] through array[519]

* …
* set 127: address 2032 to 2047, (2032 to 2047) + 2KB, …  

   * block at 2032: array[508] through array[511]
   * block at 2032+2KB: array[1020] through array[1023]



### thinking about cache storage (2)  {.smaller}


* 2KB 2-way set associative cache with 16B blocks: block addresses ---
* set 0: address 0\\tikzmark{first}, 0 +\\tikzmark{second} 2KB, 0 + 4KB, … 

   * block at 0: [array[0] through array[3]]{.fragment fragment-index=4 .custom .myem-only}
   * block at 0+1KB: [array[256] through array[259]]{.fragment fragment-index=4 .custom .myem-only}
   * block at 0+2KB: [array[512] through array[515]]{.fragment fragment-index=4 .custom .myem-only}
   * …

* set 1: address 16, 16 + 2KB, 16 + 4KB, … <br> 

   * address 16: array[4] through array[7]

* …
* set 63: address 1008, 2032 + 2KB, 2032 + 4KB …  

   * address 1008: array[252] through array[255]


