###

### last time {.smaller}

*  C code and cache misses
   *  mapping arrays to cache sets
   *  need for alignment
   *  spatial locality; "unlucky" spacing by powers of two
*  on write miss ---
   *  add to cache = _write-allocate_
   *  keep uncached = _write-no-allocate_
*  if modifying cached value, modify next level...
   *   when evicted = _write-back_
   *   immediately = _write-through_

### quiz Q2 {.smaller}

```
int GetStudentScore(char *name, int assignment_index) {
    for (int i = 0; i < 1000; i += 1) {
        if (strcmp(name, students[i].name) == 0)
            return students[i].scores[assignment_index];
    }
    return -1;
}
```

*  all names near beginning: fewer things accessed each call
    *  better temporal locality --- accessed more freuqently
*  hashtable
    *  if good hash function, things only accessed twice if same student chosen twice
    *  ... but much more efficient (fewer total accesses)
*  binary search
   *  accesses students[500].name first every time
   *  fewer total accesses
   *  $\implies$ better temporal locality

### midterm1 regrades

*  we'd strongly prefer them by next Monday

## exercise: write/replacement policies {visibility="hidden"}

{{< include /caching/_writeReplaceExercise.qmd >}}

## fast writes: write buffers {visibility="hidden"}

{{< include /caching/_fastWrites.qmd >}}

## briefly, cache tradeoffs {visibility="hidden"}

{{< include /caching/_tradeoffsBrief.qmd >}}

{{< include /caching/_cacheBenchExample.qmd >}}

# TLB {visibility="hidden"}

{{< include /vm/_twoLevelPtLib.qmd >}}

## review: page table lookup (1) {visibility="hidden"}

{{< include /vm/_twoLevelPTAlt.qmd >}}

## why cache page table entries? {visibility="hidden"}

{{< include /caching/_tlbWhy.qmd >}}

## how TLB fits in page table lookup {visibility="hidden"}

{{< include /caching/_tlbMulti.qmd >}}

## how TLBs are organized {visibility="hidden"}

{{< include /caching/_tlbOrgNoCircuit.qmd >}}


## exercise: splitting for TLBs {visibility="hidden"}

{{< include /caching/_tlbSplitEx1.qmd >}}

{{< include /caching/_tlbSplitEx2.qmd >}}

## exercise: TLB access pattern {visibility="hidden"}

{{< include /caching/_tlbAccessExPrep.qmd >}}

{{< include /caching/_tlbAccessEx.qmd >}}

{{< include /threads/_talk-inner.qmd >}}

{{< include /sync-reorder/_talk-inner.qmd >}}

# backup slides

## benchmarking and cache results {visibility="hidden"}

{{< include /caching/_cacheBenchExample.qmd >}}

###

###

