### last time {.smaller}

*  makefile rules
   *  target: prereqs(enter)(tab)command
   *  build only if "out-of-date"
   *  recursively following prereqs
*  "phony" rules (make all, make clean, ...)
*  avoiding redundancy in makefiles
   *  macros/variables
   *  CC, CFLAGS, LDFLAGS
   *  pattern rules (%.o: %.c)

### quiz logistics

# user ID idea {visibility="hidden"}

{{< include /accounts/_user-id.qmd >}}

## group IDs {visibility="hidden"}

{{< include /accounts/_group-id.qmd >}}

### identity versus permissions

* uid, gid = identity --- _who_ is running a process
* but also need _permissions_
  * _what_ can be accessed by each user
<hr/>
* most common way of storing permissions:
  *  resources (like files) have list of what identities can access them
* idea called _access control lists_

# permissions and access control lists {visibility="hidden"}

## file permissions {visibility="hidden"}

{{< include /accounts/_file-chmod.qmd >}}

{{< include /accounts/_file-acls.qmd >}}

### ACLs establish permissions 

* identity: _who_ is running a process or accessing a resource
* permissions: who has _what access_ to a file or resource
* now need _enforcement_

   * ensure that permissions are implemented correctly

# permissions exercise {visibility="hidden"}

{{< include /accounts/_ex-chmod.qmd >}}

# ACLs exercise {visibility="hidden"}

{{< include /accounts/_ex-acls-possible.qmd >}}

# enforcing permissions {visibility="hidden"}

{{< include /accounts/_auth-unix-check.qmd >}}

# superuser {visibility="hidden"}

{{< include /accounts/_auth-unix-superuser.qmd >}}

# becoming superuser {visibility="hidden"}

## on boot, /bin/login {visibility="hidden"}

{{< include /accounts/_bin-login.qmd >}}

## set-user-ID/sudo {visibility="hidden"}

{{< include /accounts/_sudo.qmd >}}

{{< include /accounts/_setuid-use.qmd >}}

## a litany of silly setuid program issues {visibility="hidden"}

{{< include /accounts/_setuid-hard-to-write.qmd >}}

# privilege escalation {visibility="hidden"}

{{< include /accounts/_priv-escalate.qmd >}}

{{< include /kernel/_talk-inner.qmd >}}
